WIP: Feature/carecon 792 add check job status
pflege-de/go-force pull request #1
Opened 2024-08-09 05:48 UTC by sBurmester

2024-08-12 09:26 UTC, vsinger commented on force/job.go
> +	job := &Job{
sind denn wirklich alle Properties vom Job "optional"? Wenn ich den Code richtig verstehe, dann wird zumindestens der ObjectMapper auf jeden Fall gebraucht (in `marshalCSV`). Das Options-Pattern wird eigentlich nur für "optionale Felder" benutzt. Alles was Pflicht ist, sollte schon als Parameter mitgegeben werden

2024-08-12 11:48 UTC, sBurmester commented on force/job.go
> +	job := &Job{
Da hast du recht. Ich hab das ganze jetzt nur umgezogen und mir noch keine Gedanken darüber gemacht was weiterhin optional bleiben kann und was nicht.

Ich werde dass auf jeden fall nochmal überdenken und anpassen. :+1:

2024-08-12 13:27 UTC, TheGoderGuy commented on force/job.go
> +func (job *Job) GetByteCount() int {
Brauchen wir die hier noch ?

2024-08-12 13:27 UTC, TheGoderGuy commented on force/job.go
> +func (job *Job) GetForceApi() *ForceApi     { return job.forceApi }
mMn können die hier raus da dass die Felder sind die wir auch dem create Job mitgeben müssen und der client immer mit default initialisiert wird. Der Ersteller das Jobs hätte immer alle Infos schon da... sehe hier keinen Mehrwert

2024-08-12 13:36 UTC, sBurmester commented on force/job.go
> +func (job *Job) GetForceApi() *ForceApi     { return job.forceApi }
Im Grunde machen die ganzen GetXyz's da keinen Sinn. Ich nehm die komplett raus

2024-08-12 14:02 UTC, vsinger requested changes

2024-08-12 14:02 UTC, vsinger commented on force/job.go
> +	if contentUrl[0:1] != `/` {
es gibt `strings.HasPrefix` was deutlich einfacher zu lesen ist :)

2024-08-12 14:02 UTC, vsinger commented on force/job.go
> +	statusURI := fmt.Sprintf("/services/data/"+job.apiVersion+"/jobs/ingest/%s", job.info.Id)
Wieso nicht alles als formattierten String, sondern zusätzlich noch String-Concatenation?

2024-08-12 14:02 UTC, vsinger commented on force/job.go
> +func (job *Job) GetByteCount() int {
bitte rausnehmen :) wird meines Wissens nur geloggt, liefert aber keinen Mehrwert

2024-08-13 06:56 UTC, sBurmester commented on force/job.go
> +	statusURI := fmt.Sprintf("/services/data/"+job.apiVersion+"/jobs/ingest/%s", job.info.Id)
Gute Frage, ist beim Umzug so mit rüber gekommen. Ich ändere das! :+1:

2024-08-13 07:23 UTC, vsinger approved these changes

2024-08-13 10:51 UTC, merged